---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-subchart
  namespace: openshift-gitops
spec:
  destination:
    namespace: kong
    server: https://kubernetes.default.svc
  project: default
  source:
    path: nginx-argo
    repoURL: https://github.com/mpaulgreen/kong-patterns
    targetRevision: main
