kong:
  ingressController:
    enabled: true
    installCRDs: false
    image:
      repository: kong/kubernetes-ingress-controller
      tag: 2.3-redhat
  image:
    repository: kong/kong-gateway
    tag: 2.8
  env:
    # database: postgres
    role: control_plane
    cluster_cert: /etc/secrets/kong-cluster-cert/tls.crt
    cluster_cert_key: /etc/secrets/kong-cluster-cert/tls.key
    # pg_user: kong
    # pg_password: kong123
    # pg_host: postgresql
  postgresql:
    enabled: false
    auth:
      username: kong
      database: kong
    image:
      # use postgres < 14 until is https://github.com/Kong/kong/issues/8533 resolved and released
      # enterprise (kong-gateway) supports postgres 14
      tag: 13.6.0-debian-10-r52
    service:
      ports:
        postgresql: "5432"
  cluster:
    enabled: true
    type: LoadBalancer
    tls:
      enabled: true
      servicePort: 8005
      containerPort: 8005
  clustertelemetry:
    enabled: true
    type: LoadBalancer
    tls:
      enabled: true
      servicePort: 8006
      containerPort: 8006
  proxy:
    enabled: true
    type: ClusterIP
  secretVolumes: 
    - kong-cluster-cert
  admin:
    enabled: true
    type: ClusterIP
    http:
      enabled: true
  enterprise:
    enabled: true
    license_secret: kong-enterprise-license
    portal:
      enabled: false
    rbac:
      enabled: false
    smtp:
      enabled: false
  manager:
    enabled: true
    type: ClusterIP